#pragma once
// Included at the END of the pinned host's nimconfig.h, for every C/C++ TU.
// Controller remains the SDK's precompiled controller; only host pools change.
#if CONFIG_IDF_TARGET_ESP32S3
#undef CONFIG_BT_NIMBLE_MEM_ALLOC_MODE_INTERNAL
#undef CONFIG_NIMBLE_MEM_ALLOC_MODE_INTERNAL
#define CONFIG_BT_NIMBLE_MEM_ALLOC_MODE_EXTERNAL 1
#endif
#undef CONFIG_BT_NIMBLE_MAX_CONNECTIONS
#define CONFIG_BT_NIMBLE_MAX_CONNECTIONS 1
#undef CONFIG_NIMBLE_MAX_CONNECTIONS
#define CONFIG_NIMBLE_MAX_CONNECTIONS 1
#undef CONFIG_BT_NIMBLE_ATT_PREFERRED_MTU
#define CONFIG_BT_NIMBLE_ATT_PREFERRED_MTU 247
#undef CONFIG_BT_NIMBLE_MAX_CCCDS
#define CONFIG_BT_NIMBLE_MAX_CCCDS 2
#undef CONFIG_BT_NIMBLE_HOST_TASK_STACK_SIZE
#define CONFIG_BT_NIMBLE_HOST_TASK_STACK_SIZE 5120
#undef CONFIG_BT_NIMBLE_MSYS_1_BLOCK_COUNT
#if defined(ROBODESK_NIMBLE_PROFILE_MSYS1_6) && ROBODESK_NIMBLE_PROFILE_MSYS1_6
#if !defined(ROBODESK_BLE_DIAGNOSTIC) || !ROBODESK_BLE_DIAGNOSTIC
#error "The reduced MSYS1 candidate is diagnostic-only until measured on C3 hardware."
#endif
#define CONFIG_BT_NIMBLE_MSYS_1_BLOCK_COUNT 6
#undef MYNEWT_VAL_MSYS_1_BLOCK_COUNT
#define MYNEWT_VAL_MSYS_1_BLOCK_COUNT 6
#else
#define CONFIG_BT_NIMBLE_MSYS_1_BLOCK_COUNT 8
#undef MYNEWT_VAL_MSYS_1_BLOCK_COUNT
#define MYNEWT_VAL_MSYS_1_BLOCK_COUNT 8
#endif
#undef CONFIG_BT_NIMBLE_MSYS_2_BLOCK_COUNT
#define CONFIG_BT_NIMBLE_MSYS_2_BLOCK_COUNT 8
#undef CONFIG_BT_NIMBLE_MSYS_2_BLOCK_SIZE
#define CONFIG_BT_NIMBLE_MSYS_2_BLOCK_SIZE 320
#undef CONFIG_BT_NIMBLE_TRANSPORT_ACL_FROM_LL_COUNT
#define CONFIG_BT_NIMBLE_TRANSPORT_ACL_FROM_LL_COUNT 8
#undef CONFIG_BT_NIMBLE_TRANSPORT_EVT_COUNT
#define CONFIG_BT_NIMBLE_TRANSPORT_EVT_COUNT 8
#undef CONFIG_BT_NIMBLE_TRANSPORT_EVT_DISCARD_COUNT
#define CONFIG_BT_NIMBLE_TRANSPORT_EVT_DISCARD_COUNT 4
#undef CONFIG_BT_NIMBLE_GATT_MAX_PROCS
#define CONFIG_BT_NIMBLE_GATT_MAX_PROCS 2
#undef MYNEWT_VAL_BLE_ATT_SVR_MAX_PREP_ENTRIES
#define MYNEWT_VAL_BLE_ATT_SVR_MAX_PREP_ENTRIES 8
// ANCS uses asynchronous GATT client procedures on the peripheral connection.
// Keep central/client support, bonding, MITM and Secure Connections enabled.
